# Coffee Exploration: Exports, Imports, and Production

This notebook adapts the existing five-part Python analysis to the three supplied CSV datasets. It explores their structure, summarizes annual values, checks data quality, and calculates findings from the available years.

**Scope note:** the CSV files do not state a measurement unit. Values below are therefore reported in the datasets’ original units. Calendar-year trade figures and coffee crop-year production figures are not directly interchangeable.

## Part 1 — Load the data

Load the CSV files from the project folder and preview the first five rows of each. The original files are left unchanged.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

DATA_FILES = {
    "Coffee Export": Path("Coffee_export-1.csv"),
    "Coffee Import": Path("Coffee_import-1.csv"),
    "Coffee Production": Path("Coffee_production-1.csv"),
}

missing_files = [str(path) for path in DATA_FILES.values() if not path.exists()]
if missing_files:
    raise FileNotFoundError(
        "Run this notebook from the project folder; missing: " + ", ".join(missing_files)
    )

datasets = {name: pd.read_csv(path) for name, path in DATA_FILES.items()}

for name, df in datasets.items():
    print(f"\n===== {name}: first five rows =====")
    display(df.head())

===== Coffee Export: first five rows =====

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
0,Angola,5040000,4260000,4800000,2340000,480000,2460000,3120000,3000000,3240000,...,480000,480000,360000,540000,660000,660000,540000,540000,1380000,43320000
1,Bolivia (Plurinational State of),9360000,4440000,5760000,2820000,5040000,5640000,7380000,6660000,5820000,...,4440000,3780000,3300000,3720000,1800000,1320000,1560000,1320000,1200000,137460000
2,Brazil,1016160000,1270980000,1127460000,1070280000,1036380000,868080000,915060000,1008060000,1088640000,...,2028360000,1712940000,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056
3,Burundi,35100000,41280000,38760000,25080000,30480000,31680000,13440000,31740000,22440000,...,13080000,23520000,11700000,15120000,13800000,12240000,10140000,12120000,17580000,646200000
4,Cameroon,156660000,105120000,98760000,42300000,32760000,24420000,33840000,82080000,44760000,...,29400000,37320000,16320000,22500000,23400000,16860000,14700000,17220000,15000000,1399920000

===== Coffee Import: first five rows =====

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
0,Austria,112800000,123480000,132360000,110160000,85020000,73860000,72600000,77640000,77580000,...,87120000,93540000,93300000,91500000,90780000,89700000,87600000,85740000,86880000,2765760000
1,Belgium,0,0,0,0,0,0,0,0,0,...,349680000,340080000,330120000,312720000,332040000,363120000,340620000,344520000,371940000,6240540000
2,Belgium/Luxembourg,120900000,104760000,109680000,123780000,135720000,144060000,151560000,152640000,214800000,...,0,0,0,0,0,0,0,0,0,1257900000
3,Bulgaria,16080000,12000000,10920000,23820000,27780000,30900000,16320000,17640000,20520000,...,28920000,33600000,36540000,37260000,40920000,46740000,42420000,44220000,47100000,830700000
4,Croatia,0,0,10080000,9780000,11580000,19200000,19320000,23100000,20340000,...,23460000,23040000,24780000,25200000,26220000,28740000,26340000,26760000,27960000,622080000

===== Coffee Production: first five rows =====

,Country,Coffee type,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
0,Angola,Robusta/Arabica,3.000000e+06,4.740000e+06,4.680000e+06,1.980000e+06,4.620000e+06,3.720000e+06,4.260000e+06,3.840000e+06,...,1.740000e+06,1.980000e+06,2.100000e+06,2.340000e+06,2.460000e+06,2.700000e+06,2.100000e+06,2.520000e+06,3.120000e+06,8.208000e+07
1,Bolivia (Plurinational State of),Arabica,7.380000e+06,6.240000e+06,7.200000e+06,3.060000e+06,7.020000e+06,8.520000e+06,7.500000e+06,8.460000e+06,...,7.920000e+06,6.300000e+06,7.200000e+06,6.000000e+06,5.040000e+06,4.680000e+06,5.040000e+06,4.980000e+06,4.860000e+06,2.070000e+08
2,Brazil,Arabica/Robusta,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10
3,Burundi,Arabica/Robusta,2.922000e+07,4.002000e+07,3.720000e+07,2.358000e+07,3.984000e+07,2.604000e+07,2.406000e+07,1.500000e+07,...,1.224000e+07,2.436000e+07,9.780000e+06,1.488000e+07,1.614000e+07,1.176000e+07,1.212000e+07,1.224000e+07,1.632000e+07,6.236400e+08
4,Ecuador,Arabica/Robusta,9.024000e+07,1.274400e+08,7.110000e+07,1.241400e+08,1.425600e+08,1.132800e+08,1.195800e+08,7.146000e+07,...,4.950000e+07,4.968000e+07,3.996000e+07,3.864000e+07,3.864000e+07,3.870000e+07,3.744000e+07,2.976000e+07,3.354000e+07,1.900380e+09

## Part 2 — Explore the datasets

The data is arranged in a wide format: each year (or production crop year) has its own column. The final `Total_...` field is an aggregate, not another year, so it is excluded from the time-series comparisons below.

In [2]:
def annual_columns(df):
    """Return year/crop-year columns, excluding the precomputed total."""
    return [
        col for col in df.columns
        if col != "Country"
        and col != "Coffee type"
        and not str(col).startswith("Total_")
    ]

structure_rows = []
for name, df in datasets.items():
    years = annual_columns(df)
    country_count = df["Country"].astype(str).str.strip().nunique()
    structure_rows.append({
        "Dataset": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Countries": country_count,
        "First period": years[0],
        "Last period": years[-1],
        "Missing cells": int(df.isna().sum().sum()),
    })

structure = pd.DataFrame(structure_rows).set_index("Dataset")
display(structure)

for name, df in datasets.items():
    print(f"\n===== {name}: column data types =====")
    display(df.dtypes.rename("Data type").to_frame())

,Rows,Columns,Countries,First period,Last period,Missing cells
Dataset,,,,,,
Coffee Export,55,32,55,1990,2019,0
Coffee Import,35,32,35,1990,2019,0
Coffee Production,55,33,55,1990/91,2019/20,0

===== Coffee Export: column data types =====

             Data type
Country            str
1990             int64
1991             int64
1992             int64
1993             int64
1994             int64
1995             int64
1996             int64
1997             int64
1998             int64
1999             int64
2000             int64
2001             int64
2002             int64
2003             int64
2004             int64
2005             int64
2006             int64
2007             int64
2008             int64
2009             int64
2010             int64
2011             int64
2012             int64
2013             int64
2014             int64
2015             int64
2016             int64
2017             int64
2018             int64
2019             int64
Total_export     int64

===== Coffee Import: column data types =====

             Data type
Country            str
1990             int64
1991             int64
1992             int64
1993             int64
1994             int64
1995             int64
1996             int64
1997             int64
1998             int64
1999             int64
2000             int64
2001             int64
2002             int64
2003             int64
2004             int64
2005             int64
2006             int64
2007             int64
2008             int64
2009             int64
2010             int64
2011             int64
2012             int64
2013             int64
2014             int64
2015             int64
2016             int64
2017             int64
2018             int64
2019             int64
Total_import     int64

===== Coffee Production: column data types =====

                 Data type
Country                str
Coffee type            str
1990/91            float64
1991/92            float64
1992/93            float64
1993/94            float64
1994/95            float64
1995/96            float64
1996/97            float64
1997/98            float64
1998/99            float64
1999/00            float64
2000/01            float64
2001/02            float64
2002/03            float64
2003/04            float64
2004/05            float64
2005/06            float64
2006/07            float64
2007/08            float64
2008/09            float64
2009/10            float64
2010/11            float64
2011/12            float64
2012/13            float64
2013/14            float64
2014/15            float64
2015/16            float64
2016/17            float64
2017/18            float64
2018/19            float64
2019/20            float64
Total_production   float64

## Part 3 — Descriptive statistics

For each dataset, summarize the distribution across annual observations (excluding aggregate-total columns). Also compare each period’s summed value. These are descriptive summaries across the dataset, not per-country averages of a single year.

In [3]:
annual_values = {}
period_totals = {}

for name, df in datasets.items():
    periods = annual_columns(df)
    values = df[periods].apply(pd.to_numeric, errors="coerce")
    annual_values[name] = values
    period_totals[name] = values.sum(axis=0, min_count=1)

    observations = values.stack().dropna()
    print(f"\n===== {name}: annual observation statistics =====")
    display(observations.describe().rename("Value").to_frame())

period_summary = pd.DataFrame({name: totals for name, totals in period_totals.items()})
period_summary.index.name = "Year / crop year"
print("\n===== Sum across countries for each period =====")
display(period_summary)

===== Coffee Export: annual observation statistics =====

              Value
count  1.650000e+03
mean   9.504439e+07
std    2.705637e+08
min   -2.147484e+09
25%    1.080000e+06
50%    8.730000e+06
75%    8.134500e+07
max    2.138220e+09

===== Coffee Import: annual observation statistics =====

              Value
count  1.050000e+03
mean   1.689898e+08
std    2.984960e+08
min    0.000000e+00
25%    1.632000e+07
50%    5.397000e+07
75%    1.847100e+08
max    1.851240e+09

===== Coffee Production: annual observation statistics =====

              Value
count  1.650000e+03
mean   1.368090e+08
std    3.911303e+08
min    0.000000e+00
25%    2.280000e+06
50%    2.103000e+07
75%    9.264000e+07
max    3.907860e+09

===== Sum across countries for each period =====

                  Coffee Export  Coffee Import  Coffee Production
Year / crop year
1990               4.840440e+09   4.447920e+09                NaN
1990/91                     NaN            NaN       5.593800e+09
1991               4.556580e+09   4.276800e+09                NaN
1991/92                     NaN            NaN       6.076140e+09
1992               4.697760e+09   4.752960e+09                NaN
1992/93                     NaN            NaN       5.911260e+09
1993               4.510020e+09   4.627080e+09                NaN
1993/94                     NaN            NaN       5.505540e+09
1994               4.242480e+09   4.501440e+09                NaN
1994/95                     NaN            NaN       5.598840e+09
1995               4.072440e+09   4.342260e+09                NaN
1995/96                     NaN            NaN       5.239260e+09
1996               4.660140e+09   4.671360e+09                NaN
1996/97                     NaN            NaN       6.198660e+09
1997               4.826280e+09   4.863780e+09                NaN
1997/98                     NaN            NaN       5.993220e+09
1998               4.814520e+09   4.966020e+09                NaN
1998/99                     NaN            NaN       6.531960e+09
1999               5.168400e+09   5.125920e+09                NaN
1999/00                     NaN            NaN       7.883040e+09
2000               5.373900e+09   5.258460e+09                NaN
2000/01                     NaN            NaN       6.824640e+09
2001               5.451600e+09   5.336940e+09                NaN
2001/02                     NaN            NaN       6.474120e+09
2002               5.330520e+09   5.475960e+09                NaN
2002/03                     NaN            NaN       7.357500e+09
2003               5.182440e+09   5.603880e+09                NaN
2003/04                     NaN            NaN       6.330180e+09
2004               5.465940e+09   5.750700e+09                NaN
2004/05                     NaN            NaN       6.964740e+09
2005               5.253840e+09   5.782620e+09                NaN
2005/06                     NaN            NaN       6.670080e+09
2006               5.505660e+09   6.094200e+09                NaN
2006/07                     NaN            NaN       8.124000e+09
2007               5.777880e+09   6.279360e+09                NaN
2007/08                     NaN            NaN       7.310520e+09
2008               5.855940e+09   6.407700e+09                NaN
2008/09                     NaN            NaN       8.088060e+09
2009               5.774700e+09   6.270780e+09                NaN
2009/10                     NaN            NaN       7.672440e+09
2010               5.822940e+09   6.548820e+09                NaN
2010/11                     NaN            NaN       8.404500e+09
2011               6.131220e+09   6.708780e+09                NaN
2011/12                     NaN            NaN       8.479620e+09
2012               6.506580e+09   6.790380e+09                NaN
2012/13                     NaN            NaN       9.071040e+09
2013               6.514140e+09   6.955680e+09                NaN
2013/14                     NaN            NaN       9.234540e+09
2014               2.545236e+09   7.201620e+09                NaN
2014/15                     NaN            NaN       9.017940e+09
2015               2.582556e+09   7.282800e+09                NaN
2015/16                     NaN            NaN       9.367560e+09
2016               7.279920e+09   7.657860e+09                NaN
2016/17                     NaN            NaN       9.739080e+09
2017               7.171380e+09   7.563840e+09                NaN
2017/18                     NaN            NaN       9.821580e+09
2018               7.595760e+09   7.796700e+09                NaN
2018/19                     NaN            NaN       1.034778e+10
2019               3.312036e+09   8.096640e+09                NaN
2019/20                     NaN            NaN       9.903180e+09

## Part 4 — Data quality assessment

Check missing cells, fully duplicated rows, country labels with leading or trailing spaces, and non-numeric values in annual fields. Import country labels are stripped only in temporary analysis expressions; the source CSV is not modified.

In [4]:
quality_rows = []
for name, df in datasets.items():
    annual = annual_values[name]
    country_text = df["Country"].astype(str)
    quality_rows.append({
        "Dataset": name,
        "Missing cells": int(df.isna().sum().sum()),
        "Duplicate rows": int(df.duplicated().sum()),
        "Country labels with extra spaces": int(country_text.str.strip().ne(country_text).sum()),
        "Non-numeric annual cells": int(annual.isna().sum().sum()),
    })

quality = pd.DataFrame(quality_rows).set_index("Dataset")
display(quality)

print("\nCountry labels that need trimming (if any):")
for name, df in datasets.items():
    labels = df.loc[
        df["Country"].astype(str).str.strip().ne(df["Country"].astype(str)),
        "Country",
    ].drop_duplicates().tolist()
    if labels:
        print(f"{name}: {labels}")
    else:
        print(f"{name}: none")

,Missing cells,Duplicate rows,Country labels with extra spaces,Non-numeric annual cells
Dataset,,,,
Coffee Export,0,0,0,0
Coffee Import,0,0,28,0
Coffee Production,0,0,0,0

Country labels that need trimming (if any):
Coffee Export: none
Coffee Import: ['   Austria', '   Belgium', '   Belgium/Luxembourg', '   Bulgaria', '   Croatia', '   Cyprus', '   Czechia', '   Denmark', '   Estonia', '   Finland', '   France', '   Germany', '   Greece', '   Hungary', '   Ireland', '   Italy', '   Latvia', '   Lithuania', '   Luxembourg', '   Malta', '   Netherlands', '   Poland', '   Portugal', '   Romania', '   Slovakia', '   Slovenia', '   Spain', '   Sweden']
Coffee Production: none

## Part 5 — Findings from the data

The trade datasets cover calendar years **1990–2019**; production covers crop years **1990/91–2019/20**. The figures below are calculated from the annual columns only, so precomputed total columns do not inflate the comparison. Since the files do not identify units, the reported values retain the original dataset units.

In [5]:
def endpoint_change(totals):
    first, last = totals.iloc[0], totals.iloc[-1]
    pct_change = (last / first - 1) * 100 if first else float("nan")
    return first, last, pct_change

finding_rows = []
for name, totals in period_totals.items():
    first, last, pct = endpoint_change(totals)
    values = annual_values[name]
    latest_period = values.columns[-1]
    country_names = datasets[name]["Country"].astype(str).str.strip()
    latest_by_country = values[latest_period].groupby(country_names).sum().sort_values(ascending=False)
    leader = latest_by_country.index[0]
    finding_rows.append({
        "Dataset": name,
        "First period": str(totals.index[0]),
        "First-period sum": first,
        "Latest period": str(totals.index[-1]),
        "Latest-period sum": last,
        "Change (%)": pct,
        "Latest-period leader": leader,
        "Leader value": latest_by_country.iloc[0],
    })

findings = pd.DataFrame(finding_rows).set_index("Dataset")
display(findings.style.format({
    "First-period sum": "{:,.0f}",
    "Latest-period sum": "{:,.0f}",
    "Change (%)": "{:+.1f}%",
    "Leader value": "{:,.0f}",
}))

print("\nTop five countries in the latest available period:")
for name, values in annual_values.items():
    latest_period = values.columns[-1]
    country_names = datasets[name]["Country"].astype(str).str.strip()
    leaders = values[latest_period].groupby(country_names).sum().sort_values(ascending=False).head(5)
    print(f"\n{name} — {latest_period}")
    display(leaders.rename("Value").to_frame())

Top five countries in the latest available period:

Coffee Export — 2019

                Value
Country
Viet Nam   1644000000
Colombia    820320000
Honduras    405900000
Indonesia   380040000
India       361680000

Coffee Import — 2019

                               Value
Country
United States of America  1851240000
Germany                   1345920000
Italy                      654840000
Japan                      482400000
France                     479580000

Coffee Production — 2019/20

                  Value
Country
Brazil     3.492660e+09
Viet Nam   1.829220e+09
Colombia   8.460000e+08
Indonesia  6.859800e+08
Ethiopia   4.405800e+08

### Interpretation

- Across reporting countries, **coffee exports decreased 31.6%** from **4,840,440,000** in 1990 to **3,312,036,352** in 2019. Viet Nam was the largest exporter in 2019 at **1,644,000,000**, followed by Colombia at **820,320,000**.
- The summed **coffee imports increased 82.0%**, from **4,447,920,000** in 1990 to **8,096,640,000** in 2019. The United States of America was the largest importer in 2019 at **1,851,240,000**, followed by Germany at **1,345,920,000**.
- Summed coffee production increased **77.0%** between crop years 1990/91 (**5,593,800,000**) and 2019/20 (**9,903,180,000**). Brazil led production in 2019/20 at **3,492,660,000**; it also had the largest cumulative sum across the listed crop years (**75,082,980,000**).
- The import file has **28 country labels with surrounding spaces out of 35 rows**. All three files have **zero missing cells and zero fully duplicated rows**. Trimming labels in analysis avoids inconsistent display, but any permanent cleanup should preserve the original source files.

**Cautions:** the country coverage differs among export, import, and production datasets; their sums are not a complete global trade balance. Production uses crop years while trade uses calendar years, and no unit is specified in the files. These data describe reported totals but do not explain the causes of trends.

In [6]:
print("Coffee Exploration Analysis Complete!")

Coffee Exploration Analysis Complete!